name: Example workflow for Snyk Infrastructure as Code,
on: push
permissions:
      id-token: write
      contents: read
      packages: read
jobs:
   snyk:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master

      - name: Run Snyk Code
        continue-on-error: true
        run: snyk iac test --sarif=snyk-code-report.sarif > snyk-code-report.sarif
        env:
          SNYK_TOKEN: "bd232314-6d92-48dd-a7e8-1add00d92be0"
       
      - run: |
           ls -al
      - uses: actions/upload-artifact@v2
        with:
          name: SARIF
          path: snyk-code-report.sarif
       
      - name: Upload the SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-code-report.sarif
